title: 焦点的动力炉 | Jiao Dian's Power Plant
author: dianjiaogit
email: jiaodianmail@gmail.com
description: > # this means to ignore newlines until "show_excerpts:"
  This is Jiao Dian's blog. A place for sharing notes about my thoughts. Just for FUN.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: dianjiao
    github:  dianjiaogit
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - todo.md
# - work.md
 - about.md
# - categories.md

# Build settings
#jekyll-archives:
#  enabled:
#    - categories
#  layout: 'archive'
#  layouts:
#    year: year-archive
#    month: month-archive
#    tag: tag-archive-layout

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
# - jekyll-archives
